language: python
cache: pip
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO_VERSION=1.11.26
  - DJANGO_VERSION=2.2.8
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=1.11.26 DRF_VERSION=3.9.2
  - DJANGO_VERSION=2.2.8 DRF_VERSION=3.9.2
  - DJANGO_VERSION=3.0 DRF_VERSION=3.9.2
install:
  - pip install -r .travis/requirements.txt
  - pip install --upgrade "Django==${DJANGO_VERSION}"
  - if [[ $DRF_VERSION ]]; then pip install --upgrade djangorestframework==${DRF_VERSION}; fi
script: python runtests.py
