language: python
cache: pip
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.2
  - DJANGO_VERSION=1.8.18 DRF_VERSION=3.5.3
  - DJANGO_VERSION=1.9.13 DRF_VERSION=3.5.3
  - DJANGO_VERSION=1.10.7 DRF_VERSION=3.5.3
  - DJANGO_VERSION=1.11.2 DRF_VERSION=3.5.3
install:
  - pip install -r .travis/requirements.txt
  - pip install --upgrade "Django~=${DJANGO_VERSION}"
  - if [[ $DRF_VERSION ]]; then pip install --upgrade djangorestframework~=${DRF_VERSION}; fi
script: python runtests.py
