language: python
cache: pip
python:
  - 2.7
  - 3.6
env:
  - DJANGO_VERSION=1.11.15
  - DJANGO_VERSION=2.0.8
  - DJANGO_VERSION=2.1.1
  - DJANGO_VERSION=1.11.15 DRF_VERSION=3.8.2
  - DJANGO_VERSION=2.0.8 DRF_VERSION=3.8.2
  - DJANGO_VERSION=2.1.1 DRF_VERSION=3.8.2
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO_VERSION=2.1.1
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO_VERSION=2.1.1 DRF_VERSION=3.8.2
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0.8
    - python: 2.7
      env: DJANGO_VERSION=2.0.8 DRF_VERSION=3.8.2
    - python: 2.7
      env: DJANGO_VERSION=2.1.1
    - python: 2.7
      env: DJANGO_VERSION=2.1.1 DRF_VERSION=3.8.2
install:
  - pip install -r .travis/requirements.txt
  - pip install --upgrade "Django==${DJANGO_VERSION}"
  - if [[ $DRF_VERSION ]]; then pip install --upgrade djangorestframework==${DRF_VERSION}; fi
script: python runtests.py
